language: php

php: [5.5, 5.6]

install: phpenv config-rm xdebug.ini

before_script:
  - composer install -o --prefer-source
  - ./app/console doctrine:database:create

script:
  - ./bin/phpunit -c app
  - ./bin/behat

after_failure: "cat app/logs/*.log"
