imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false


parameters:
  test.client.parameters:
    HTTP_ACCEPT:
    HTTP_ACCEPT_LANGUAGE:
    HTTP_ACCEPT_CHARSET:
