api_docs:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc

players_post:
  path:     /players
  defaults: { _controller: mpwar.controller.player.post:__invoke }
  methods:  [POST]
