services:

  mpwar.player.infrastructure.player_repository:
    alias: mpwar.player.infrastructure.player_repository.mysql

  mpwar.player.infrastructure.player_repository.in_memory:
    class: MPWAR\Module\Player\Infrastructure\Persistence\PlayerRepositoryInMemory

  mpwar.player.infrastructure.player_repository.mysql:
    class: MPWAR\Module\Player\Infrastructure\Persistence\PlayerRepositoryMySql
    arguments:
      - @doctrine.orm.entity_manager
