services:

  # Command Handlers

  mpwar.player.command_handler.player_registration:
    class: MPWAR\Module\Player\Application\CommandHandler\PlayerRegistrationCommandHandler
    arguments:
      - @mpwar.player.service.player_registrar
    tags:
      - { name: command_handler, handles: MPWAR\Module\Player\Contract\Command\PlayerRegistration }

  # Query Handlers

  mpwar.player.query_handler.player_find:
    class: MPWAR\Module\Player\Application\QueryHandler\PlayerFindQueryHandler
    arguments:
      - @mpwar.player.service.player_finder
    tags:
      - { name: query_handler, handles: MPWAR\Module\Player\Contract\Query\PlayerFind }


  # Services

  mpwar.player.service.player_registrar:
    class: MPWAR\Module\Player\Application\Service\PlayerRegistrar
    arguments:
      - @mpwar.player.infrastructure.player_repository
      - @event_bus
    public: false

  mpwar.player.service.player_finder:
    class: MPWAR\Module\Player\Application\Service\PlayerFinder
    arguments:
      - @mpwar.player.infrastructure.player_repository
    public: false
